apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: monitoring-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: vinaykumarrajanna/monitoring-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://192.168.49.2:32000"  
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: monitoring-dashboard
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
